Repository Sprint-Part3-14Team/14team-project, pull requests merged in 2024-06, with the labels that each got.

#2 🎨 style: 테일윈드 공통 색상 추가 및 pretendard 폰트 추가
  app/layout.tsx
  app/page.tsx
  public/fonts/PretendardVariable.woff2
  tailwind.config.ts
Labels: 📦chore

#13 💄 design: #5 -로그인 및 회원가입 페이지 디자인
  .eslintrc.json
  app/(auth)/_components/input-field.tsx
  app/(auth)/_components/password-input-field.tsx
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/(auth)/layout.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  package.json
  pnpm-lock.yaml
  public/icons/icon_visibility.png
  public/images/auth_logo.png
Labels: 💄design

#20 ✨feat: #9 공용 버튼 컴포넌트 생성
  app/components/Buttons.tsx
  app/page.tsx
Labels: ✨feat

#18 ✨feat: #8 사이드바 대시보드 리스트 생성
  app/(dashboard)/dashboard/page.tsx
  app/(dashboard)/layout.tsx
  app/(dashboard)/mydashboard/page.tsx
  app/api/dashboard/getDashboards.ts
  app/components/sidebar/sidebar-dashboard-list.tsx
  app/components/sidebar/sidebar.tsx
  app/page.tsx
  constants/TEAM_BASE_URL.ts
  public/icons/add_dashboard.svg
  public/icons/crown_icon.svg
  public/images/logo_small.svg
  public/images/text_logo.svg
  types/dashboard.ts
Labels: ✨feat

#25 💄design: #7 헤더, 사이드바, 메인 영역 구분
  app/(dashboard)/layout.tsx
  app/components/navbar/navbar.tsx
  app/components/sidebar/sidebar.tsx
  app/page.tsx
Labels: 💄design

#21 ✨ feat: #15 로그인 및 회원가입 구현 완료
  app/(auth)/_components/input-field.tsx
  app/(auth)/_components/password-input-field.tsx
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/(auth)/signin/actions.ts
  app/(auth)/signup/actions.ts
  lib/schemas/auth.ts
  package.json
  pnpm-lock.yaml
  public/icons/icon_visibility.png
  public/icons/icon_visibility_off.png
  types/auth.ts
Labels: ✨feat

#23 💄 design: 랜딩 페이지 하단에 위치한 광고 카드 컴포넌트 생성
  app/components/landing_components/ad-card.tsx
  app/layout.tsx
  public/images/landing3.png
  public/images/landing4.png
  public/images/landing5.png
Labels: 💄design

#29 🐛!HOTFIX: 로그인, 회원가입 fetch 수정
  app/(auth)/signin/actions.ts
  app/(auth)/signup/actions.ts
Labels: 🐛fix

#30 ♻️refactor: 쿠키에 있는 토큰 사용하여 대시보드 리스트 로직 수정
  app/api/dashboard/getDashboards.ts
  constants/TEAM_BASE_URL.ts
Labels: ♻️refactor

#33 ✨feat: 회원 이미지 프로필 컴포넌트 생성
  app/components/profile/profile-image.tsx
  app/components/sidebar/sidebar-profile.tsx
  app/components/sidebar/sidebar.tsx
  constants/profileColorList.ts
  hooks/useProfileColor.ts
  types/user.ts
Labels: ✨feat

#31 💄 design: 대시보드 카드 컴포넌트 추가
  .eslintrc.json
  app/(dashboard)/_components/dashboard-card.tsx
  app/(dashboard)/_components/tag.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/dashboard/page.tsx
  app/(dashboard)/layout.tsx
  next.config.mjs
  public/icons/icon_calendar.svg
Labels: 💄design

#35 ✨feat: #19 아이콘 버튼 컴포넌트 생성
  app/components/buttons.tsx
  app/components/icon-buttons.tsx
  app/page.tsx
  public/icons/add_dashboard.svg
  public/icons/add_invite.svg
  public/icons/setting_icon.svg
Labels: ✨feat

#41 ✨ feat : 랜딩 페이지 전체 구현
  app/components/landing/ad-card.tsx
  app/components/landing/point-card.tsx
  app/components/landing/sns-link-icon.tsx
  app/page.tsx
  pnpm-lock.yaml
  public/icons/email_icon.svg
  public/icons/facebook_icon.svg
  public/icons/instagram_icon.svg
  public/images/landing/landing1.png
  public/images/landing/landing2.png
  public/images/landing/landing3.png
  public/images/landing/landing4.png
  public/images/landing/landing5.png
  public/images/landing/main.png
Labels: 💄design

#39 💄 design: 대시보드 디자인 구현
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/(dashboard)/_components/dashboard-card.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/layout.tsx
  public/icons/icon_add_column.svg
Labels: 💄design

#43 💄desgin: 대시보드 헤더 생성
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/(dashboard)/dashboard/[id]/layout.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/layout.tsx
  app/components/sidebar/sidebar.tsx
Labels: 💄design

#49 🐛 !HOTFIX: 대시보드 fetch 데이터 수정
  app/(dashboard)/dashboard/[id]/page.tsx
Labels: 🐛fix

#52 🐛fix: 머지 후 main 영역 스타일 깨지는 문제 수정
  app/(dashboard)/dashboard/[id]/layout.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/layout.tsx
  app/(dashboard)/mydashboard/page.tsx
Labels: 🐛fix, 💄design

#53 ✨feat: #10 공용 모달 컴포넌트 생성
  app/components/modals.tsx
Labels: ✨feat

#57 💄 design: 오랜 반응형 숙원 해결
  app/(dashboard)/dashboard/[id]/layout.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/layout.tsx
Labels: 🐛fix, 💄design

#58 ✨feat: #50 로그인/회원가입 페이지 모달 컴포넌트
  app/(auth)/_components/auth-modal.tsx
Labels: ✨feat

#59 💄 design: pagination 버튼 컴포넌트 UI 추가
  app/components/pagination/page-button.tsx
  public/icons/arrow_forward.svg
  public/icons/arrow_next.svg
Labels: 💄design

#62 ✨ feat: 대시보드 페이지 데이터 패칭 추가
  app/(dashboard)/_components/todo-card.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  next.config.mjs
Labels: ✨feat

#63 💄design: #61 mydashboard 대시보드 리스트 반응형 구현
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/page.tsx
Labels: 💄design

#67 💄 design: 대시보드 디자인 마무리
  app/(dashboard)/_components/todo-card.tsx
  app/(dashboard)/dashboard/[id]/layout.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  utils/formatDate.ts
Labels: 💄design

#66 ✨ feat: 미들웨어를 이용하여 로그인 및 회원가입 리다이렉트 설정
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/login/actions.ts
  app/(auth)/login/page.tsx
  app/(auth)/signup/actions.ts
  app/(auth)/signup/page.tsx
  app/page.tsx
  middleware.ts
Labels: ✨feat

#64 ♻️refactor: 버튼 및 모달 컴포넌트 리팩토링
  app/(auth)/_components/auth-modal.tsx
  app/components/button.tsx
  app/components/buttons.tsx
  app/components/icon-buttons.tsx
  app/components/modal.tsx
  app/page.tsx
Labels: 🐛fix, ♻️refactor

#70 ✨feat: 대시보드 헤더 생성
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/(dashboard)/dashboard/[id]/layout.tsx
  types/members.ts
Labels: ✨feat

#68 ✨ feat: /edit 페이지 대시보드 추가
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/color-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/color-radio.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-info-change.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/section-title.tsx
  app/(dashboard)/dashboard/[id]/edit/actions.ts
  app/(dashboard)/dashboard/[id]/edit/page.tsx
  app/(dashboard)/mydashboard/_components/dashboard-card.tsx
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/components/pagination/page-button.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  constants/DASHBOARD_COLOR_LIST.ts
  public/icons/arrow_forward_black.svg
  public/icons/arrow_forward_gray.svg
  public/icons/check-icon.svg
  types/dashboard.ts
Labels: ✨feat, 💄design

#76 ✨feat: 대시보드 멤버 리스트
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-member-list.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/components/navbar/navbar.tsx
  app/components/profile/profile-image.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨feat

#78 🐛fix: 대시보드 타입 변경으로 인한 오류 해결
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
Labels: 🐛fix

#80 💄design: 대시보드 헤더 버튼 디자인 수정 및 수정페이지 연결
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/components/icon-buttons.tsx
Labels: 💄design

#83 ✨ feat: 비밀번호 변경 로직 설정
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/(dashboard)/_components/edit-password-form.tsx
  app/(dashboard)/_components/edit-profile-form.tsx
  app/(dashboard)/mypage/actions.ts
  app/(dashboard)/mypage/page.tsx
  app/components/input-field.tsx
  lib/schemas/profileUpdate.ts
  types/profileUpdate.ts
Labels: ✨feat

#81 💄design: 대시보드생성 모달 디자인 구현
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/components/color-list.tsx
  app/components/color-ratio.tsx
Labels: 💄design

#84 ✨feat: 초대받은 대시보드 리스트 데이터 패칭 및 UI 구현
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/_components/invitation-card.tsx
  app/(dashboard)/mydashboard/_components/invitation-list.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/components/button.tsx
  app/components/sidebar/sidebar.tsx
  public/icons/search.svg
  types/dashboard.ts
  types/invitations.ts
Labels: ✨feat, 💄design

#91 ✨feat: 초대받은 대시보드 리스트 무한스크롤 구현
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/_components/invitation-list.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/(dashboard)/mydashboard/actions.ts
  app/components/sidebar/sidebar-dashboard-list.tsx
  constants/TEAM_BASE_URL.ts
  package.json
  pnpm-lock.yaml
  types/invitations.ts
Labels: ✨feat

#90 ✨ feat: 프로필 및 닉네임 변경 로직 구현
  app/(dashboard)/_components/edit-password-form.tsx
  app/(dashboard)/_components/edit-profile-form.tsx
  app/(dashboard)/mypage/actions.ts
  app/(dashboard)/mypage/page.tsx
  app/components/image-input-field.tsx
  app/components/input-field.tsx
  lib/schemas/profileUpdate.ts
  types/profileUpdate.ts
Labels: ✨feat

#89 💄 design:/edit pagination 데이터 컴포넌트 스타일링
  app/(dashboard)/dashboard/[id]/edit/_components/list/data-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/list/delete-item-button.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/list/list-container.tsx
  app/(dashboard)/dashboard/[id]/edit/page.tsx
Labels: 💄design

#85 '✨ feat: /edit 페이지 내 대시보드 삭제버튼 추가
  app/(dashboard)/dashboard/[id]/edit/_components/delete-dashboard-button.tsx
  app/(dashboard)/dashboard/[id]/edit/page.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨feat, 💄design

#96 ✨feat: 초대 응답 기능 구현
  app/(dashboard)/mydashboard/_components/invitation-card.tsx
  app/(dashboard)/mydashboard/_components/invitation-list.tsx
  app/(dashboard)/mydashboard/_components/invitation-response-button.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/(dashboard)/mydashboard/actions.ts
  app/(dashboard)/mydashboard/page.tsx
Labels: ✨feat

#100 ✨ feat: 컴파운드 패턴을 이용한 드롭다운
  app/components/dropdown.tsx
  app/test/page.tsx
  public/icons/arrow_down.svg
Labels: ✨feat

#102 ✨ feat: 대시보드 생성 토큰 리팩토링
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/(dashboard)/mydashboard/postActions.ts
Labels: ✨feat, ♻️refactor
