Repository Sprint-Part3-14Team/14team-project, pull requests merged in 2024-07, with the labels that each got.

#103 💄design: #97 카드 생성 모달 디자인 구현
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-button.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/assignee-user-dropdown.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  app/(dashboard)/mydashboard/page.tsx
  app/components/dropdown.tsx
  app/components/input-field.tsx
  app/test/page.tsx
  hooks/useProfileColor.ts
Labels: 💄design

#101 💄 design: 마이페이지 디자인
  app/(dashboard)/_components/edit-password-form.tsx
  app/(dashboard)/_components/edit-profile-form.tsx
  app/(dashboard)/mypage/page.tsx
  app/components/image-input-field.tsx
  app/globals.css
  app/layout.tsx
  components.json
  components/ui/sonner.tsx
  lib/utils.ts
  package.json
  pnpm-lock.yaml
  public/icons/icon_purple_add.svg
  tailwind.config.ts
Labels: ✨feat, 💄design

#104 ✨ feat: 로그인 에러 핸들링 및 빈 토큰 값 버그 수정
  app/(auth)/_components/auth-modal.tsx
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/(auth)/login/actions.ts
  app/(auth)/signup/actions.ts
Labels: ✨feat

#105 💄 design: 비슷한 모달 (생성, 관리, 초대) 디자인 구현
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/components/single-input-modal.tsx
Labels: 💄design

#107 ✨ feat: /edit pagination 추가
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-info-change.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation-card.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/list/data-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/list/delete-item-button.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/list/list-container.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/member/member-card.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/member/member-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/member/member.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/section-title.tsx
  app/(dashboard)/dashboard/[id]/edit/actions.ts
  app/(dashboard)/dashboard/[id]/edit/page.tsx
  app/components/pagination/page-button.tsx
  constants/TEAM_BASE_URL.ts
  public/icons/arrow_next_black.svg
  public/icons/arrow_next_gray.svg
  types/invitations.ts
  types/members.ts
Labels: ✨feat

#115 🐛 fix: 변경 데이터 패칭, 컬러 checked 표시
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/color-radio.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-info-change.tsx
  app/(dashboard)/dashboard/[id]/edit/actions.ts
  public/icons/checked.svg
Labels: 🐛fix

#111 ✨ feat: 마이페이지 이메일 및 닉네임 기본 값 추가
  app/(dashboard)/_components/edit-profile-form.tsx
Labels: ✨feat

#117 🐛 HOTFIX: 초대하기 버튼 추가, 페이지네이션 버튼 수정, section props 수정
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-info-change.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation-button.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation.tsx
Labels: 🐛fix

#116 ✨ feat: 초대하기 모달 생성
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/actions.ts
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/invite-button.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/invite-modal.tsx
  app/components/navbar/navbar.tsx
  app/components/single-input-modal.tsx
  lib/schemas/inviteEmail.ts
Labels: ✨feat

#123 🐛 fix: 빌드 에러 해결
  app/globals.css
  app/layout.tsx
  package.json
Labels: 🐛fix

#119 ✨ feat: 수정페이지 초대하기 버튼
  app/(dashboard)/dashboard/[id]/edit/_components/invitation/invitation-button.tsx
Labels: ✨feat

#132 ✨feat: #125 태그 랜덤 색상 구현
  app/(dashboard)/_components/tag.tsx
  app/(dashboard)/_components/todo-card.tsx
  app/(dashboard)/_components/todo-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-tag-input.tsx
  constants/tagColorList.ts
  hooks/useTagColor.ts
Labels: ✨feat

#133 ✨ feat: 새 칼럼 생성 모달
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/actions.ts
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-button.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-modal.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  lib/schemas/columnName.ts
Labels: ✨feat

#134 ♻️refactor: #126 할 일 카드 생성 기능 보완
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/action.ts
Labels: ♻️refactor

#127 ✨ feat: /mydashboard 내부 대시보드 목록 페이지네이션
  app/(dashboard)/mydashboard/_components/dashboard-card.tsx
  app/(dashboard)/mydashboard/_components/dashboard-list.tsx
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/actions.ts
  types/dashboard.ts
Labels: ✨feat

#137 ✨ feat: 댓글 디자인, CRUD 구현
  app/(dashboard)/_components/todo-modal-comment-list.tsx
  app/(dashboard)/_components/todo-modal-comment.tsx
  app/(dashboard)/_components/todo-modal.tsx
  app/(dashboard)/dashboard/[id]/action.ts
  app/components/navbar/navbar-profile.tsx
  types/commentData.ts
  utils/formDateHour.ts
Labels: ✨feat, 💄design

#138 ✨ feat: 칼럼 관리 모달
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/actions.ts
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/delete-warning-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/edit-column-button.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/edit-column-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-modal.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
Labels: ✨feat

#142 ✨ feat: 댓글 인피니티 스크롤 구현
  app/(dashboard)/_components/todo-modal-comment-list.tsx
  app/(dashboard)/_components/todo-modal-comment.tsx
  constants/TODO_MODAL_COMMENT.ts
Labels: ✨feat

#140 🐛 fix: 칼럼 생성 / 수정 모달 버그 수정
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/edit-column-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-button.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/invite-button.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/invite-modal.tsx
  app/components/single-input-modal.tsx
Labels: 🐛fix

#141 ✨feat: #124 카드 수정 기능 구현
  app/(dashboard)/_components/todo-card.tsx
  app/(dashboard)/_components/todo-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-due-date-input.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-title-input.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/assignee-user-dropdown.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/column-dropdown.tsx
  app/(dashboard)/dashboard/[id]/action.ts
  app/components/dropdown.tsx
  app/components/image-input-field.tsx
  lib/schemas/createToDo.ts
  types/card.ts
  types/toDoCard.ts
Labels: ✨feat, ♻️refactor

#152 💄design: #144 사이드바, 프로필 드롭다운 디자인 변경
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/layout.tsx
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/components/image-input-field.tsx
  app/components/navbar/navbar-profile.tsx
  app/components/navbar/navbar.tsx
  app/components/profile/profile-image.tsx
  app/components/sidebar/sidebar-button.tsx
  app/components/sidebar/sidebar-dashboard-card.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  app/components/sidebar/sidebar.tsx
  public/images/none_invitation.svg
Labels: 💄design

#151 💄design: color-picker 기능 추가
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/components/PrelineScript.tsx
  app/components/color-picker.tsx
  app/layout.tsx
  package.json
  pnpm-lock.yaml
  tailwind.config.ts
Labels: 💄design

#148 🐛 fix: 대시보드 페이지네이션 버그 수정
  app/(dashboard)/mydashboard/_components/dashboard-list.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  app/components/sidebar/sidebar-dashboard.tsx
  utils/makeDashboardResponse.ts
Labels: 🐛fix

#145 ✨ feat: 검색 input 값이 변경될 때마다 데이터 패칭
  app/(dashboard)/mydashboard/_components/invitation-container.tsx
  app/(dashboard)/mydashboard/_components/invitation-list.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  app/(dashboard)/mydashboard/actions.ts
  hooks/useDebounce.ts
Labels: ✨feat

#154 🐛 fix: 폼 버그 수정
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/assignee-user-dropdown.tsx
  app/(dashboard)/mydashboard/_components/invitations.tsx
  lib/schemas/createToDo.ts
  types/toDoCard.ts
Labels: 🐛fix

#158 ✨feat: #143 대시보드 수정 버튼 비활성화 처리
  app/(dashboard)/_components/todo-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-due-date-input.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-tag-input.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-button.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/assignee-user-dropdown.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/column-dropdown.tsx
  app/(dashboard)/dashboard/[id]/action.ts
  app/components/column-tag.tsx
  app/components/image-input-field.tsx
  lib/schemas/createToDo.ts
  types/toDoCard.ts
Labels: ✨feat, ♻️refactor

#157 ♻️ refactor: 사이드바 페이지 버튼 위치 수정 및 마지막 페이지 체크, debounce 추가
  app/(dashboard)/mydashboard/_components/invitation-container.tsx
  app/components/color-list.tsx
  app/components/color-ratio.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
  app/components/sidebar/sidebar-dashboard.tsx
  app/components/sidebar/sidebar.tsx
  constants/TEAM_BASE_URL.ts
  hooks/useDebounce.ts
  utils/debounce.ts
  utils/makeDashboardResponse.ts
Labels: 🐛fix, ♻️refactor

#159 🐛 fix: 이미지가 공백이여도 기본 프로필 이미지로 추가 및 수정 버튼 로직 변경
  app/(dashboard)/_components/edit-profile-form.tsx
  app/(dashboard)/mypage/actions.ts
  app/components/image-input-field.tsx
Labels: 🐛fix

#160 ✨ feat: 로그아웃 구현
  app/components/navbar/navbar-profile.tsx
Labels: ✨feat

#161 ✨ feat: 담당자와 마감일이 없을 때 텍스트 수정
  app/(dashboard)/_components/todo-modal.tsx
Labels: ✨feat

#162 ♻️ refactor: 대시보드 생성 모달 마이그레이션
  app/(dashboard)/dashboard/[id]/_components/to-do/assignee-user-dropdown.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/column-dropdown.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/color-list.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/color-radio.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/mydashboard/_components/actions.ts
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/components/color-list.tsx
  app/components/color-picker.tsx
  app/components/color-radio.tsx
Labels: ♻️refactor

#164 💄 design: 대시보드 프로필 ml 및 이미지 인풋 스타일 변경
  app/(dashboard)/_components/todo-card.tsx
  app/components/image-input-field.tsx
Labels: 💄design

#166 💄design: 로고 변경
  app/(auth)/layout.tsx
  app/components/navbar/navbar.tsx
  app/page.tsx
  public/images/checkbox_logo.png
  public/images/crown_logo.png
  public/images/todo_todo_text_logo.svg
Labels: 💄design

#165 💄 design: 라이트모드 구현
  app/components/landing/ad-card.tsx
  app/components/navbar/navbar.tsx
  app/components/pagination/page-button.tsx
  app/components/sidebar/sidebar-dashboard-card.tsx
  app/globals.css
  app/page.tsx
  components/mode-toggle.tsx
  components/ui/button.tsx
  components/ui/dropdown-menu.tsx
  package.json
  pnpm-lock.yaml
Labels: 💄design

#171 💄design: hover 시 색 변경, 애니메이션 등 전체적인 디자인 수정
  app/(auth)/_components/auth-modal.tsx
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/new-column-button.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-button.tsx
  app/(dashboard)/dashboard/[id]/_components/to-do/add-to-do-modal.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/delete-dashboard-button.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/member/member-card.tsx
  app/(dashboard)/mydashboard/_components/dashboard-card.tsx
  app/(dashboard)/mydashboard/_components/dashboards.tsx
  app/(dashboard)/mydashboard/_components/invitation-response-button.tsx
  app/components/button.tsx
  app/components/color-list.tsx
  app/components/color-radio.tsx
  app/components/column-tag.tsx
  app/components/dropdown.tsx
  app/components/icon-buttons.tsx
  app/components/navbar/navbar-profile.tsx
  app/components/pagination/page-button.tsx
  app/components/sidebar/sidebar-dashboard-card.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  constants/DASHBOARD_COLOR_LIST.ts
  constants/tagColorList.ts
  public/images/landing/main.png
Labels: 💄design

#169 🐛 fix: 대시보드 이름 수정 시 사이드바 이름 미변경
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/invite-modal.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-info-change.tsx
  app/(dashboard)/dashboard/[id]/edit/actions.ts
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
Labels: ✨feat, 🐛fix

#172 ♻ refactor: 초대하기, 칼럼 생성, 수정 모달 disable 처리 / 디자인 수정
  app/(dashboard)/dashboard/[id]/_components/dashboard-column/delete-warning-modal.tsx
  app/components/single-input-modal.tsx
Labels: 💄design, ♻️refactor

#173 💄 design: 토스트 디자인 수정
  components/ui/sonner.tsx
Labels: 💄design

#174 💄 design: 파비콘 설정
  app/layout.tsx
Labels: 💄design

#175 💄design: 사이드바 버튼 디자인 수정
  app/(auth)/_components/sign-in-form.tsx
  app/(auth)/_components/sign-up-form.tsx
  app/components/sidebar/sidebar-button.tsx
  app/page.tsx
  public/images/clipboard.svg
Labels: 💄design

#179 💄design: 대시보드 글자수 제한 및 페이지네이션 버튼 수정
  app/(dashboard)/_components/todo-modal.tsx
  app/(dashboard)/dashboard/[id]/edit/_components/dashboard/dashboard-change-form.tsx
  app/(dashboard)/mydashboard/_components/new-dashboard-modal.tsx
  app/components/color-list.tsx
  app/components/color-picker.tsx
  app/components/color-radio.tsx
  app/components/sidebar/sidebar-dashboard-card.tsx
  app/components/single-input-modal.tsx
  app/globals.css
  app/layout.tsx
  components/mode-toggle.tsx
Labels: 💄design, ♻️refactor

#180 🐛HOTFIX: 중복 확인 조건 추가
  app/(dashboard)/mydashboard/_components/dashboard-list.tsx
  app/components/sidebar/sidebar-dashboard-list.tsx
Labels: 🐛fix

#181 🐛 fix: 초대받은 사람에서 초대한 사람으로 변경
  app/(dashboard)/mydashboard/_components/invitation-card.tsx
Labels: 🐛fix

#182 🐛 fix: 대시보드 페이지에서 초대하기 버튼 조건부 렌더링 적용
  app/(dashboard)/dashboard/[id]/_components/dashboard-navbar/dashboard-navbar.tsx
Labels: 🐛fix

#183 💄 design: 다크 모드 이미지 반영
  app/(dashboard)/mypage/page.tsx
Labels: 💄design

#184 💄fix: 버튼 색 변경
  app/(dashboard)/_components/edit-password-form.tsx
Labels: 💄design

#185 ♻️ refactor: edit page error.tsx 추가
  app/(dashboard)/dashboard/[id]/edit/actions.ts
  app/(dashboard)/dashboard/[id]/edit/error.tsx
  app/(dashboard)/mydashboard/actions.ts
  types/apiErrorResponse.ts
Labels: ♻️refactor
